name: Called Action
inputs:
  action:
    description: 'Github Action'
    required: true
    type: string
    default: "example"

runs:
  using: composite
  steps:
    - name: Dump text for baseline
      shell: bash
      run: |
         echo "----------------------"
         echo "This is the INPUT received for this ACTION"
         echo "input: ${{ inputs.action }}"
         echo "----------------------"
         echo "This is the INPUT received for this WORKFLOW"
         echo "input: ${{ github.event.inputs.some_string }}"
         echo "----------------------"
         echo "These are pulled from github.event... "
         echo "PR number: ${{ github.event.pull_request.number }}"
         echo "Event action: ${{ github.event.action }}"
         echo "PR head SHA: ${{ github.event.pull_request.head.sha }}"
         echo "Workflow run ID: ${{ github.run_id }}"
         echo "Run attempt: ${{ github.run_attempt }}"
